### ISSUE TITLE
Using Spinn for SNLI

### ISSUE THREAD

**Issue by omidb** [hans/spinn#3]
Hi, 

Would you please provide the specific command to run Spinn with the checkpoint data on SNLI-like input string.

Thanks

**Comment by abhirast** [comment]
The commands for running pre-trained models are now present [here] (https://github.com/hans/spinn/blob/master/checkpoints/commands.sh). A test run over snli-like inputs can be done by changing the flag --eval_data_path $EVAL_DATA suitably, where EVAL_DATA is the path to a file like snli_1.0_test.jsonl,  and adding the flags  --eval_output_path $OUTPUT_PATHS, --expanded_eval_only_mode and --write_predicted_label. The last two flags are boolean and OUTPUT_PATH is a path of the desired output. The script then creates a file named OUTPUT_PATH.lbl containing the predicted labels.

The flags --eval_data_path and --eval_output_path can also take a list of paths concatenated by the character ':'. The number of specified paths by the two flags must be the same. The definition of these flags can be found [here](https://github.com/hans/spinn/blob/master/python/models/fat_classifier.py#L763).
